# Site
title:              J Haigh
bio:                "Rust Developer | DenverFP co-organizer | Rust Boulder/Denver co-organizer | Runner of a Haskell Book Club | Occasional author of blog posts | Speaker | Hopeful about the future of programming"
description:        "I'm very passionate about Haskell and Rust and would like to share the joy I've found in learning those languages with others. Strong and static types help make me more confident that my code will work in the future."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/background.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://DebugSteven.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   username

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-108012933-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              DebugSteven@gmail.com
twitter:            DebugSteven
#facebook:           username
github-url:         DebugSteven
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           j-haigh-a80988106
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://twitter.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
